<?php
/**
 * Implements hook_menu().
 */
function my_forms_menu() {
 
  $items = array();
  $items['contact-page'] = array(
    'title' => 'Contacts',
    'page callback' => 'contact_page_content',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
  );
 
  return $items;
}

function contact_page_content() {
drupal_set_message(t('form was subm' . <br> 
	. $form_state['value'] ['phone number']
	));  
  
  $form = '
<!--noindex--> 
  <form action = "my_forms.module.php" method="POST">
    <div >
      <label for="name">Name</label>
      <input type="text" name="name">
    </div>
    <div>
      <label for="name">Surname</label>
      <input type="text" name="name">
    </div>
    <div>
      <label for="name">Nick(*)</label>
      <input type="text" name="name"required>
    </div>
    <div>
      <label for="name">Email(*)</label>
      <input type="text" name="name"required>
    </div>
    <div>
      <label for="name">Telefone number</label>
      <input type="text" name="name"required>
    </div>
    <label for="name">Sex</label>
      <input type="text" name="name"required>
    </div>
    <div style>
    <label for="name">Country</label> 
    <select size="3" multiple name="country[]">
    <option >Select country</option>
    <option value="Ukraine">Ukraine</option>
    <option value="Russia">Russia</option>
    <option value="USA">USA</option>
               </select>
    </div>
    <div>
      <label for="name">Message(*)</label>
      <input type="textarea" name="name"required>
    </div>
    <p><b>С какими операционными системами вы знакомы?</b></p>
    <p><input type="checkbox" name="option1" value="a1" checked>Windows 95/98</p>
    <fieldset>
   <legend>Работа со временем</legend>
     <input type="checkbox"> создание пунктуальности (никогда не 
      будете никуда опаздывать);<br>
     <input type="checkbox"> излечение от пунктуальности (никогда 
      никуда не будете торопиться);<br>
     <input type="checkbox"> изменение восприятия времени и часов.
      <p><input type="submit"></p>
  </fieldset>



      <input type="password" name="pass">
    </div>

    <input type="submit" name="submit" value="Submit">
     </form><!--/noindex-->
';

return 'Enter your contacts in form below' . $form;

} 
?>