<?php
/**
 * Implements hook_menu().
 */
function my_forms_menu() {
 
  $items = array();
  $items['contact-page'] = array(
    'title' => 'Contacts',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('my_forms_page_form'),
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
  );
 
  return $items;
}

/**
 * Build form.
 */
function my_forms_page_form($form, $form_state) {
  $form = array();
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#description' => "Please enter yuor name.",
    '#size' => 20,
  );
  $form['surname'] = array(
    '#type' => 'textfield',
    '#title' => t('Surname'),
    '#description' => "Please enter yuor surname.",
    '#size' => 20,
  );
  $form['nickname'] = array(
    '#type' => 'textfield',
    '#title' => t('Nickname'),
    '#required' => TRUE,
    '#description' => "Please enter yuor nickname.",
    '#size' => 20,
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#required' => TRUE,
    '#default_value' => "",
    '#description' => "Please enter your email.",
    '#size' => 20,
    '#maxlength' => 20,
    '#element_validate' => array('MODULE_email_element_validate'),
);
  
  $form['number'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone number'),
    '#description' => "Please enter yuor phone number.",
    '#maxlength' => 10,
    '#size' => 20,
    '#element_validate' => array('element_validate_integer'), //build in function
  );  

  $form['sex'] = array( 
    '#type' => 'radios',
    '#title' => t('Yuor sex'),
    '#options' => array('man' => t('Мan'), 'woman' => t('Woman')),
    '#description' => "Please point yuor sex.",
    '#size' => 20,
  );

  $form['country'] = array( 
    '#type' => 'select',
    '#title' => t('Country'),
    '#options' => array('Ukraine' => t('Ukraine'), 'Russia' => t('Russia'), 'USA' => t('USA')),
    '#description' => "Please select yuor country.",
  );

  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#required' => TRUE,
    '#description' => "Please enter yuor message.",
  );  

  $form['rules'] = array(
    '#type' => 'checkbox',
    '#title' => t('Approval of rules'),
    '#required' => TRUE,
    '#description' => "I accept all regulations.",
  );      
  
  $form['fieldset'] = array(
    '#title' => 'Fieldset',
    '#type' => 'fieldset',
  );
  $form['fieldset']['markup'] = array(
    '#markup' => '<p>Fill all fields of form and press submit</p>',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}  
// email validation function
  function MODULE_email_element_validate($element, &$form_state, $form) {
   if (!valid_email_address($element['#value'])) {
     form_error($element, t('Please enter a valid email address.'));
  }
}
/**
 * Submit function for my_forms_page_form.
 */
function my_forms_page_form_submit($form, &$form_state) {
    drupal_set_message('Form sumitted! your data:');
    drupal_set_message("Your name: " .
    $form_state['values']['name']);
    drupal_set_message("Your surname: " .
    $form_state['values']['surname']);
    drupal_set_message("Your nickname: " .
    $form_state['values']['nickname']);
    drupal_set_message("Your email: " .
    $form_state['values']['email']);
    drupal_set_message("Your phone number: " .
    $form_state['values']['number']);
    drupal_set_message("Your sex: " .
    $form_state['values']['sex']);
    drupal_set_message("Your country: " .
    $form_state['values']['country']);
    drupal_set_message("Your message: " .
    $form_state['values']['message']);
}  